### ISSUE TITLE
the  error of  lims.sql

### ISSUE THREAD

**Issue by jmsong2** [Jianwei-Zhang/LIMS#1]
When i run command "source /LIMS-master/sql/lims.sql", I got  ERROR 1064.
![image](https://cloud.githubusercontent.com/assets/23074979/19722712/9143d6a8-9baa-11e6-857a-27e70ec72368.png)

It seems like a syntax error.
I think maybe "`note` longtext COMMENT," could change to "`note` longtext COMMENT '',".

**Comment by Jianwei-Zhang** [comment]
bug fixed by removing the "COMMENT" attribute.
